import { FormEvent, useEffect, useState } from 'react'
import { Message } from '../components/Message'
import { apiRequest } from '../services/api'
import type { CatalogItem, Purchase, ShoppingListItem } from '../types'

export function ShoppingListPage({ token }: { token: string }) {
  const [items, setItems] = useState<ShoppingListItem[]>([]), [catalog, setCatalog] = useState<CatalogItem[]>([])
  const [selected, setSelected] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [locked, setLocked] = useState(false)
  async function load() { setLoading(true); setError(''); try { const [listResult, catalogResult, purchaseResult] = await Promise.all([apiRequest<{ items: ShoppingListItem[] }>('/shopping-list', {}, token), apiRequest<{ items: CatalogItem[] }>('/catalog', {}, token), apiRequest<{ purchase: Purchase | null }>('/purchases/active', {}, token)]); setItems(listResult.items); setCatalog(catalogResult.items); setLocked(purchaseResult.purchase?.status === 'IN_PROGRESS') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  async function add(event: FormEvent) { event.preventDefault(); if (!selected) return; try { await apiRequest('/shopping-list/items', { method: 'POST', body: JSON.stringify({ catalogItemId: selected }) }, token); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado') } }
  async function patch(id: string, update: object) { try { await apiRequest(`/shopping-list/items/${id}`, { method: 'PATCH', body: JSON.stringify(update) }, token); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado') } }
  async function remove(id: string) { try { await apiRequest(`/shopping-list/items/${id}`, { method: 'DELETE' }, token); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Error inesperado') } }
  if (loading) return <p>Cargando...</p>
  return <section><h2>Lista de compras</h2><Message error={error} />{locked && <p className="message">La lista está bloqueada porque hay una compra en curso.</p>}<form className="inline" onSubmit={add}><select value={selected} onChange={(e) => setSelected(e.target.value)} disabled={locked}><option value="">Seleccionar producto</option>{catalog.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={locked || !selected}>Agregar</button></form><div className="list">{items.length === 0 && <p>La lista está vacía.</p>}{items.map((item) => <div className="list-row" key={item.id}><div><strong>{item.name}</strong>{item.urgent && <span className="urgent"> Urgente</span>}<small>Comprado: {item.purchasedQuantity} de {item.quantity}</small></div><div className="actions"><input aria-label={`Cantidad de ${item.name}`} type="number" min="1" defaultValue={item.quantity} disabled={locked} onBlur={(e) => Number(e.target.value) !== item.quantity && void patch(item.id, { quantity: Number(e.target.value) })} /><label className="check"><input type="checkbox" checked={item.urgent} disabled={locked} onChange={(e) => void patch(item.id, { urgent: e.target.checked })} /> Urgente</label><button className="danger" disabled={locked} onClick={() => void remove(item.id)}>Quitar</button></div></div>)}</div></section>
}
